### ISSUE TITLE
NoClassDefFoundError: org/jetbrains/kotlin/resolve/source/PsiSourceElementKt indexing square/okhttp repo

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/scip-kotlin#9]
Running `lsif-java index` in the square/okhttp repo
```
e: java.lang.NoClassDefFoundError: org/jetbrains/kotlin/resolve/source/PsiSourceElementKt
	at com.sourcegraph.semanticdb_kotlinc.GlobalSymbolsCache.getAllMethods(SymbolsCache.kt:253)
	at com.sourcegraph.semanticdb_kotlinc.GlobalSymbolsCache.methodDisambiguator(SymbolsCache.kt:197)
	at com.sourcegraph.semanticdb_kotlinc.GlobalSymbolsCache.semanticdbDescriptor(SymbolsCache.kt:178)
	at com.sourcegraph.semanticdb_kotlinc.GlobalSymbolsCache.uncachedSemanticdbSymbol-BfSPOvA(SymbolsCache.kt:109)
	at com.sourcegraph.semanticdb_kotlinc.GlobalSymbolsCache.getSymbol-BfSPOvA(SymbolsCache.kt:71)
	at com.sourcegraph.semanticdb_kotlinc.GlobalSymbolsCache.emitSymbols(SymbolsCache.kt:51)
	at com.sourcegraph.semanticdb_kotlinc.GlobalSymbolsCache.access$emitSymbols(SymbolsCache.kt:30)
	at com.sourcegraph.semanticdb_kotlinc.GlobalSymbolsCache$get$1.invokeSuspend(SymbolsCache.kt:40)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:140)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
```

@Strum355 This looks like a Kotlin compiler version incompatibility. Do you think we'll need to cross-build/cross-publish the semanticdb-kotlinc compiler plugin?

**Comment by Strum355** [comment]
From what I could tell, theyre using a version I had tested with https://github.com/square/okhttp/blob/master/buildSrc/src/main/kotlin/deps.kt#L24, will have to take a closer look 🧐
